### ISSUE TITLE
How to use this with python GTK bindings?

### ISSUE THREAD

**Issue by emmggi** [mjakeman/text-engine#20]
Sorry for the noob question. 

I'm interested in building a rich text notes app using GTK and python. With python you use [https://pygobject.readthedocs.io/en/latest/](pygobject) to create GTK apps and i'm not sure how to incorporate this one.

Thank you for this framework.

**Comment by mjakeman** [comment]
Hi, thanks for the interest

At the moment text-engine is nowhere near ready to be used in creating apps. While I've made substantial progress in the last few months, there's a long way to go before it is 'plug-and-play'.

It currently supports paragraph based layouts and simple traversal (left/right/up/down + home and end), as well as the usual insertion/deletion/splitting operations you would want to do on text. Beyond that, it's not terribly useful for doing real rich-text editing as it cannot render formatting yet. 

Unfortunately the truth is there's no good option for rich text in Gtk at the moment. If you don't mind waiting, I'm hoping to have basic formatting and support for lists and images done by the end of the year. Otherwise GtkTextView can do a lot of simple formatting (bold/italic/underline) and might be powerful enough for what you're looking for?
